---
title: "Sentiment Analysis in R"
author: "Jenn Schilling"
date: "9/16/2021"
output: html_document
---

This file contains the code for webinar: [Sentiment Analysis in R](https://www.airweb.org/collaborate-learn/calendar/2021/10/20/event/sentiment-analysis-in-r), presented for the Association for Institutional Research, October 20 & 22 2021.  

**Webinar Details**  
This webinar will teach participants how to complete a text analysis in R, including data processing and cleaning, visualization of word frequencies, and sentiment analysis. Sentiment analysis is useful for finding patterns in text data from open response questions on surveys and course evaluations as well as evaluating social media posts. This series is ideal for higher education professionals who have some experience in R and want to add text analysis to their R skills.

As a result of this webinar, participants will be able to: 
- Prepare data for a text analysis in R. 
- Conduct text mining in R.
- Complete sentiment analysis in R. 

**Materials developed by Jenn Schilling.**  

```{r setup, message = FALSE}

library(here) # working directory
library(tidyverse) # data processing and plotting
library(tidytext) # text analysis

# Read data
text_data <- read_csv(here("data", "uarizona_tweets.csv"), )

```


